version: "3.8"

services:
  postgres-compose: 
    image: postgres
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

      